
export const FETCH_PRODUCT_REQUIST = "FETCH_PRODUCT_REQUIST"

export const FETCH_PRODUCT_SUCESSS = "FETCH_PRODUCT_SUCESSS"

export const FETCH_PRODUCT_ERROR = "FETCH_PRODUCT_ERROR"



export const FETCH_SINGLE_REQUIST = "FETCH_SINGLE_REQUIST"

export const FETCH_SINGLE_SUCESSS = "FETCH_SINGLE_SUCESSS"

export const FETCH_SINGLE_ERROR = "FETCH_SINGLE_ERROR"

export const FETCH_CARD_PRODUCT_REQUIST = "FETCH_SINGLE_REQUIST"

export const FETCH_CARD_PRODUCT_SUCESSS = "FETCH_SINGLE_SUCESSS"

export const FETCH_CARD_PRODUCT_ERROR = "FETCH_SINGLE_ERROR"

export const USER_DETAIL_INFO_REQUIST = "USER_DETAIL_INFO_REQUIST"

export const USER_DETAIL_INFO_SUCESSS = "USER_DETAIL_INFO_SUCESSS"

export const USER_DETAIL_INFO_ERROR = "USER_DETAIL_INFO_ERROR"

